# naive bayes classifier on Iris data

## Imports to be used

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
from sklearn.metrics import confusion_matrix
print("imports completed\n")

imports completed



## reading and formating data

In [2]:
data = pd.read_csv("datasets_19_420_Iris.csv")
data.drop(["Id"],axis=1,inplace=True)
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

## splitting data

In [3]:
data.to_numpy() #converting data to numpy array
X = data.iloc[:,:4].values
y = data['Species'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 34)
print("split succesful with ratio ",X_train.shape,X_test.shape)


split succesful with ratio  (120, 4) (30, 4)


homeginizing data using fit and transform method

In [4]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print("homogenized data eg\n", X_train[:10,:4])

homogenized data eg
 [[ 1.20059723  0.37892538  1.02467475  1.34024382]
 [-1.02490008 -0.0997172  -1.25546988 -1.34450533]
 [-1.49342583  0.37892538 -1.36669644 -1.34450533]
 [ 0.61494005  0.37892538  0.35731535  0.31748224]
 [-1.25916295  0.85756796 -1.08863003 -1.34450533]
 [-0.7906372   0.85756796 -1.36669644 -1.34450533]
 [ 0.49780861 -1.77496623  0.30170206  0.06179185]
 [-1.25916295 -0.0997172  -1.36669644 -1.21666013]
 [ 0.96633436  0.61824667  1.02467475  1.59593422]
 [ 1.0834658   0.37892538  1.13590132  1.34024382]]


## fitting and predicting data

In [5]:
classifier.fit(X_train,y_train)
y_predict=classifier.predict(X_test)
compare = np.vstack((y_predict,y_test)).T
print("comparing predicted output with test output \n",compare[:,:10],"\n")

comparing predicted output with test output 
 [['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-ver

## using confusion matrix to check validity of classifier

In [6]:
cm = confusion_matrix(y_predict,y_test)
print("confusion matirx is \n",cm,"\n")
total=cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2]
accuracy=(cm[1,1]+cm[2,2])/total
print("accuracy of classification model is ",accuracy )

confusion matirx is 
 [[11  0  0]
 [ 0 14  0]
 [ 0  1  4]] 

accuracy of classification model is  0.9473684210526315
